_target_: src.models.sr_module.SRLitModule
net:
  _target_: src.models.components.imsisr.IMSISR
  in_channels: 3
  n_resblocks: 16
  n_feats: 64
  kernel_size: 3 
  res_scale: 1.
  rgb_range: 1.

lr: 0.0001