defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

model:
  _target_: src.models.sr_module.SRLitModule
  arch: diinn
  mode: 3
  init_q: False
  lr: 1e-4
  lr_gamma: 0.5
  lr_step: 10
  eval_bsize: 30000

trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: .
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  callbacks:
  - _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: -1
  - _target_: pytorch_lightning.callbacks.RichProgressBar
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: null
    filename: null
    monitor: val/loss
    verbose: false
    save_last: true
    save_top_k: 1
    save_weights_only: false
    mode: min
    auto_insert_metric_name: true
  devices: auto
  check_val_every_n_epoch: 1
  fast_dev_run: false
  max_epochs: 50
  min_epochs: 10
  max_steps: -1
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  accelerator: auto
  strategy:
    _target_: pytorch_lightning.strategies.DDPStrategy
    process_group_backend: gloo
  sync_batchnorm: true
  precision: 32
  
  reload_dataloaders_every_n_epochs: 0

data:
  _target_: src.datamodules.sr_datamodule.SRDataModule
  root: ./data/
  trainsets:
  - - DIV2K
    - train
  trainsets_repeat: 20
  testsets:
  - - DIV2K
    - train
  - - benchmark
    - B100
  - - benchmark
    - Set5
  - - benchmark
    - Set14
  - - benchmark
    - Urban100
  batch_size: 1
  train_scales:
  - 2
  - 3
  - 4
  test_scales:
  - 2
  - 2.5
  - 3
  - 3.5
  - 4
  - 6
  - 8
  - 10
  - 15
  - 20
  patch_size: 48
  num_workers: 8
  pin_memory: False
