#!/bin/bash
#SBATCH --job-name=metasr
#SBATCH --output=metasr
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mail-type=all
#SBATCH --mail-user=hquan@lanl.gov
#SBATCH --qos=standard
#SBATCH --time=16:00:00
#SBATCH -p gpu

eval "$(conda shell.bash hook)"
cd /lustre/scratch5/hquan/projects/sisr
conda activate clat
python main.py fit -c configs/default.yaml --model=SRLitModule --model.arch=metasr --trainer.logger=TensorBoardLogger --trainer.logger.save_dir=logs/ --trainer.logger.name=metasr