#!/bin/bash

#SBATCH -J implicit-sr     # Job name
#SBATCH -o myjob.o%j       # Name of stdout output file
#SBATCH -e myjob.e%j       # Name of stderr error file
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 00:30:00        # Run time (hh:mm:ss)
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A scene-gen-gan   # Project/Allocation name (req'd if you have more than 1)
#SBATCH --mail-user=quan.nguyen4@mavs.uta.edu

# Any other commands must follow all #SBATCH directives...
cd $WORK/projects/implicit-sr
conda activate implicit-sr
git reset --hard
git pull origin master
# Launch serial code...
python src/train.py --data_dir="$WORK/datasets/DIV2k"
